version: '3'

services:
  symba-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/symba-cpython:2.1.0
    volumes:
      - ./pyproject.toml:/opt/symba/pyproject.toml
      - ./README.md:/opt/symba/README.md
      - ./setup.py:/opt/symba/setup.py
      - ./src:/opt/symba/src
      - ./symba:/opt/symba/symba
      - ./tests:/opt/symba/tests
    entrypoint: pytest
