version: '3'

services:
  symba-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/symba-pypy:2.2.0-alpha
    volumes:
      - ./pyproject.toml:/opt/symba/pyproject.toml
      - ./README.md:/opt/symba/README.md
      - ./setup.py:/opt/symba/setup.py
      - ./symba:/opt/symba/symba
      - ./tests:/opt/symba/tests
    entrypoint: pytest
